services:
  # --- Authentication ---
  keycloak:
    build:
      context: ./keycloak-event-listener
    container_name: keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://${NEON_DB_HOST}/keycloak_db?sslmode=require
      - KC_DB_USERNAME=${NEON_DB_USER}
      - KC_DB_PASSWORD=${NEON_DB_PASSWORD}
      - KC_HOSTNAME_URL=http://localhost:8088
      - KC_HOSTNAME_ADMIN_URL=http://localhost:8088
      - KAFKA_URL=${KAFKA_URL}
      - KAFKA_KEY=${KAFKA_KEY}
      - KAFKA_SECRET=${KAFKA_SECRET}

    ports:
      - "8088:8080"
    networks:
      - social_media_net
    restart: unless-stopped

  # --- Gateway ---
  api-gateway:
    build:
      context: ./api-gateway
      network: host
    container_name: api-gateway
    ports: [ "9000:9000" ]
    networks: [ social_media_net ]
    depends_on:
      keycloak:
        condition: service_started
    environment:
      - SERVER_PORT=9000
      - spring.cloud.gateway.routes[0].id=user-service
      - spring.cloud.gateway.routes[0].uri=http://user-service:8080
      - spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/users/**
      - spring.cloud.gateway.routes[1].id=post-service
      - spring.cloud.gateway.routes[1].uri=http://post-service:8080
      - spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/posts/**
      - spring.cloud.gateway.routes[2].id=social-account-service
      - spring.cloud.gateway.routes[2].uri=http://social-account-service:8080
      - spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/accounts/**, /api/v1/internal/**
      - spring.cloud.gateway.routes[3].id=analytics-service
      - spring.cloud.gateway.routes[3].uri=http://analytics-service:8080
      - spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/analytics/**
      - spring.cloud.gateway.routes[4].id=media-service
      - spring.cloud.gateway.routes[4].uri=http://media-service:8080
      - spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/media/**
      - spring.cloud.gateway.routes[5].id=ai-service
      - spring.cloud.gateway.routes[5].uri=http://ai-service:8080
      - spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/ai/**
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://localhost:8088/realms/user-service
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/user-service/protocol/openid-connect/certs

  # --- Producers ---
  post-service:
    build:
      context: ./post-service
    container_name: post-service
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${NEON_DB_HOST}/post_service_db?sslmode=require
      - SPRING_DATASOURCE_USERNAME=${NEON_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${NEON_DB_PASSWORD}
      - KAFKA_URL=${KAFKA_URL}
      - KAFKA_KEY=${KAFKA_KEY}
      - KAFKA_SECRET=${KAFKA_SECRET}
      - CLIENTS_SOCIAL_ACCOUNT_SERVICE_URL=http://social-account-service:8080
      - CLIENTS_ANALYTICS_SERVICE_URL=http://analytics-service:8080
      - CLIENTS_MEDIA_SERVICE_URL=http://media-service:8080
    networks: [ social_media_net ]

  social-account-service:
    build:
      context: ./social-account-service
    container_name: social-account-service
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${NEON_DB_HOST}/social_account_service_db?sslmode=require
      - SPRING_DATASOURCE_USERNAME=${NEON_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${NEON_DB_PASSWORD}
      - KAFKA_URL=${KAFKA_URL}
      - KAFKA_KEY=${KAFKA_KEY}
      - KAFKA_SECRET=${KAFKA_SECRET}
      - LINKEDIN_CLIENT_ID=${LINKEDIN_CLIENT_ID}
      - LINKEDIN_CLIENT_SECRET=${LINKEDIN_CLIENT_SECRET}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://localhost:8088/realms/user-service
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/user-service/protocol/openid-connect/certs

    networks: [ social_media_net ]

  # --- Consumers ---
  scheduler-service:
    build:
      context: ./scheduler-service
    container_name: scheduler-service
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${NEON_DB_HOST}/scheduler_service_db?sslmode=require
      - SPRING_DATASOURCE_USERNAME=${NEON_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${NEON_DB_PASSWORD}
      - KAFKA_URL=${KAFKA_URL}
      - KAFKA_KEY=${KAFKA_KEY}
      - KAFKA_SECRET=${KAFKA_SECRET}
      - CLIENTS_SOCIAL_ACCOUNT_SERVICE_URL=http://social-account-service:8080
      - KAFKA_CLIENTID=scheduler-consumer-docker-1
    networks: [ social_media_net ]

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    depends_on:
      - keycloak
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${NEON_DB_HOST}/user_service_db?sslmode=require
      - SPRING_DATASOURCE_USERNAME=${NEON_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${NEON_DB_PASSWORD}
      - KAFKA_URL=${KAFKA_URL}
      - KAFKA_KEY=${KAFKA_KEY}
      - KAFKA_SECRET=${KAFKA_SECRET}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://localhost:8088/realms/user-service
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/user-service/protocol/openid-connect/certs

    networks: [ social_media_net ]

  analytics-service:
    build:
      context: ./analytics-service
    container_name: analytics-service
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${NEON_DB_HOST}/analytics_service_db?sslmode=require
      - SPRING_DATASOURCE_USERNAME=${NEON_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${NEON_DB_PASSWORD}
      - KAFKA_URL=${KAFKA_URL}
      - KAFKA_KEY=${KAFKA_KEY}
      - KAFKA_SECRET=${KAFKA_SECRET}
      - CLIENTS_SOCIAL_ACCOUNT_SERVICE_URL=http://social-account-service:8080
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks: [ social_media_net ]

  # --- Support Services ---
  media-service:
    build:
      context: ./media-storage-service
    container_name: media-service
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${NEON_DB_HOST}/media_service_db?sslmode=require
      - SPRING_DATASOURCE_USERNAME=${NEON_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${NEON_DB_PASSWORD}
      - MINIO_URL=${MINIO_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - BUCKET=${BUCKET}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://localhost:8088/realms/user-service
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/user-service/protocol/openid-connect/certs
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks: [ social_media_net ]

  ai-service:
    build:
      context: ./ai-service
    container_name: ai-service
    depends_on:
      - keycloak
      - media-service
    environment:
      - SERVER_PORT=8080
      - GROQ_API_KEY=${GROQ_API_KEY}
      - CLIENTS_MEDIA_SERVICE_URL=http://media-service:8080
      - KAFKA_URL=${KAFKA_URL}
      - KAFKA_KEY=${KAFKA_KEY}
      - KAFKA_SECRET=${KAFKA_SECRET}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://localhost:8088/realms/user-service
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URcdI=http://keycloak:8080/realms/user-service/protocol/openid-connect/certs
    networks: [ social_media_net ]


volumes:
  post-data:
  scheduler-data:
  social-account-data:
  analytics-data:
  user-data:
  media-data:
  keycloak_db_data:
  minio_data:

networks:
  social_media_net:
    driver: bridge